version: "3.1"

services:
  app:
    image: bankinfo:v1
    ports:
      - "3366:8080"
    environment:
      - DB_DRIVER=${DB_DRIVER}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME_DATABASE=${DB_NAME_DATABASE}
      - DB_HOST_DATABASE=${DB_HOST_DATABASE}
      - DB_PORT_DATABASE=${DB_PORT_DATABASE}
    restart: unless-stopped
